# Generated by Django 3.1.7 on 2021-02-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
